version: "3.3"
services:
  backoffice:
    container_name: samebro_backoffice
    build: .
    restart: always
    image: tomcat:8.5-jdk11-openjdk-slim
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - samebro-network
    expose:
      - ${BACKOFFICE_PORT}
    ports:
      - ${BACKOFFICE_PORT}:8080

networks:
  samebro-network:

volumes:
  dbvolume:
