version: "3.3"
services:
  db:
    image: mysql:8.1.0
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - samebro-network
    volumes:
      - dbvolume:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:3306"

  api:
    container_name: samebro_backend
    build: .
    restart: always
    image: tomcat:8.5-jdk11-openjdk-slim
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - samebro-network
    expose:
      - ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:8080
    depends_on:
      - db

networks:
  samebro-network:

volumes:
  dbvolume:
